export const EventTypes = {
	HTTP_RESPONSE: "HTTP_RESPONSE",
	BOOKING_CREATED: "BOOKING_CREATED",
	BOOKING_UPDATED: "BOOKING_UPDATED",
	BOOKING_DELETED: "BOOKING_DELETED",
	COURT_ADDED: "COURT_ADDED",
	COURT_UPDATED: "COURT_UPDATED",
};
